'use client';

import { useEffect } from 'react';
import { addCollection } from '@iconify/react';

import type { IconifyJSON } from '@iconify/react';

let loaded = false;

/**
 * Registers the offline icon bundle (generated by scripts/generate-iconify-bundle.mjs)
 * so icons are served from our own origin instead of api.iconify.design.
 * Loaded as a separate chunk to keep the main bundle small; the Iconify API
 * remains a fallback for any icon missing from the bundle.
 */
export function IconifyLoader() {
  useEffect(() => {
    if (loaded) return;
    loaded = true;
    import('./iconify-bundle.json').then((m) => {
      for (const collection of m.default as unknown as IconifyJSON[]) addCollection(collection);
    });
  }, []);

  return null;
}
