'use client';

import { useEffect } from 'react';
import { addCollection, setCustomIconsLoader } from '@iconify/react';

import bundledPrefixes from './iconify-prefixes.json';

import type { IconifyJSON } from '@iconify/react';

let bundle: Promise<IconifyJSON[]> | null = null;

/**
 * Fetches the offline icon bundle (generated by scripts/generate-iconify-bundle.mjs,
 * shipped as its own chunk to keep the main bundle small) and registers every
 * collection once. Safe to call repeatedly.
 */
export function loadIconBundle() {
  bundle ??= import('./iconify-bundle.json').then((m) => {
    const collections = m.default as unknown as IconifyJSON[];
    for (const collection of collections) addCollection(collection);
    return collections;
  });
  return bundle;
}

// Route every bundled prefix through the bundle instead of api.iconify.design.
// Registered at module scope so it is in place before the first <Icon> asks for
// data; icons that render before the chunk arrives simply wait for it. Prefixes
// that are not bundled still fall back to the public API.
if (typeof window !== 'undefined') {
  for (const prefix of bundledPrefixes) {
    setCustomIconsLoader(
      async () => (await loadIconBundle()).find((c) => c.prefix === prefix) ?? null,
      prefix
    );
  }
}

/** Starts downloading the bundle as soon as the app mounts */
export function IconifyLoader() {
  useEffect(() => {
    loadIconBundle();
  }, []);

  return null;
}
