import { Icon } from '@iconify/react';

import mapData from './mapData.json';

import type { CSSProperties } from 'react';

import './LocationMap.scss';

type Point = readonly number[];

const { width, height, places, graticule } = mapData;

/** Positions an HTML label over a point of the map's viewBox */
const at = ([x, y]: Point): CSSProperties => ({
  left: `${(x / width) * 100}%`,
  top: `${(y / height) * 100}%`,
});

/**
 * Dotted map of the British Isles and nearby Europe with a beacon on
 * Peterborough. The dots are generated by scripts/generate-map-points.mjs.
 */
export function LocationMap({ location }: { location: string }) {
  const home = places.home;

  return (
    <figure className="location-map glass">
      <div className="location-map__chart">
        <svg
          className="location-map__svg"
          viewBox={`0 0 ${width} ${height}`}
          preserveAspectRatio="xMidYMid meet"
          aria-hidden="true"
          focusable="false"
        >
          <defs>
            <linearGradient id="location-map-uk" x1="0" y1="0" x2="1" y2="1">
              <stop offset="0" className="location-map__stop-start" />
              <stop offset="1" className="location-map__stop-end" />
            </linearGradient>
            <radialGradient id="location-map-glow">
              <stop offset="0" className="location-map__glow-core" />
              <stop offset="1" className="location-map__glow-edge" />
            </radialGradient>
          </defs>

          <g className="location-map__graticule">
            {graticule.x.map((x) => (
              <line key={`x${x}`} x1={x} x2={x} y1={0} y2={height} />
            ))}
            {graticule.y.map((y) => (
              <line key={`y${y}`} x1={0} x2={width} y1={y} y2={y} />
            ))}
          </g>

          <circle className="location-map__halo" cx={home[0]} cy={home[1]} r={70} />
          <path className="location-map__land" d={mapData.land} />
          <path className="location-map__uk" d={mapData.uk} />

          <g className="location-map__beacon">
            <circle className="location-map__ping" cx={home[0]} cy={home[1]} r={7} />
            <circle
              className="location-map__ping location-map__ping--late"
              cx={home[0]}
              cy={home[1]}
              r={7}
            />
            <circle className="location-map__pin" cx={home[0]} cy={home[1]} r={4.5} />
          </g>
        </svg>

        <span className="location-map__label" style={at(home)} aria-hidden="true">
          {location.split(',')[0]}
        </span>
      </div>

      <figcaption className="location-map__caption">
        <span className="location-map__caption-icon" aria-hidden="true">
          <Icon icon="ph:broadcast-bold" width={18} height={18} />
        </span>
        <span>
          Transmitting from <b>{location}</b>. Remote across the UK &amp; EU.
        </span>
      </figcaption>
    </figure>
  );
}

export default LocationMap;
